In [1]:
import os
import pandas as pd
import plotly.express as px

#listar todos as tabelas da pasta
lista_arquivo = os.listdir(f'C:\Dev\Estudos\ProjetoVendas\Vendas')
print(lista_arquivo)

#criar uma tabela vazia 
tabela_total = pd.DataFrame()

#lógica para extrais só os arquivos de venda
for arquivo in lista_arquivo:
    if 'Vendas' in arquivo:
        
        #ler e importar os arquivos de venda 
        tabela = pd.read_csv(f'C:\Dev\Estudos\ProjetoVendas\Vendas\{arquivo}')
        
        #copilar todas as tabelas em uma 
        tabela_total = tabela_total.append(tabela)

print(tabela_total)

#Calcular o produto mais vendido em quantidade
tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[['Quantidade Vendida']].sort_values(by='Quantidade Vendida', ascending=False)
print(tabela_produtos)

#Produto que mais faturou 
tabela_total ['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']
print(tabela_total)

tabela_faturamento = tabela_total.groupby('Produto').sum()
print(tabela_faturamento)
tabela_faturamento = tabela_faturamento[['Faturamento']].sort_values(by='Faturamento', ascending=False)
print(tabela_faturamento)
tabela_loja = tabela_total.groupby('Loja').sum()
print(tabela_loja)

grafico = px.bar(tabela_loja, x=tabela_loja.index , y='Faturamento')
grafico.show()

['Devolucoes - Belo Horizonte.csv', 'Devolucoes - Curitiba.csv', 'Devolucoes - Fortaleza.csv', 'Devolucoes - Goiás.csv', 'Devolucoes - Porto Alegre.csv', 'Devolucoes - Recife.csv', 'Devolucoes - Rio de Janeiro.csv', 'Devolucoes - Salvador.csv', 'Devolucoes - São Paulo.csv', 'Vendas - Belo Horizonte.csv', 'Vendas - Curitiba.csv', 'Vendas - Fortaleza.csv', 'Vendas - Goiás.csv', 'Vendas - Porto Alegre.csv', 'Vendas - Recife.csv', 'Vendas - Rio de Janeiro.csv', 'Vendas - Salvador.csv', 'Vendas - São Paulo.csv']

C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tabela_total = tabela_total.append(tabela)
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tabela_total = tabela_total.append(tabela)
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tabela_total = tabela_total.append(tabela)
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tabela_total = tabela_total.append(tabela)
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tabela_total = tabela_total.append(tabela)
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tabela_total = tabela_total.append(tabela)
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tabela_total = tabela_total.append(tabela)
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tabela_total = tabela_total.append(tabela)
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tabela_total = tabela_total.append(tabela)
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:25: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  tabela_produtos = tabela_total.groupby('Produto').sum()
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:33: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  tabela_faturamento = tabela_total.groupby('Produto').sum()
C:\Users\Windows\AppData\Local\Temp\ipykernel_10048\1728676591.py:37: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  tabela_loja = tabela_total.groupby('Loja').sum()

      Unnamed: 0     SKU     Produto  Quantidade Vendida Primeiro Nome  \
0             17  HL4379   Televisão                   2      Carolina
1             25  HL4379   Televisão                   1        Danilo
2             27  HL1918      iPhone                   5       Bernard
3             54  HL1918      iPhone                   5         Lucas
4             67  HL8851    Notebook                   5      Bernardo
...          ...     ...         ...                 ...           ...
2221        9981  HL7348  SmartWatch                   4          João
2222        9984  HL1918      iPhone                   4          Itai
2223        9985  HL1918      iPhone                   1     Guilherme
2224        9991  HL7348  SmartWatch                   5       Antônio
2225        9996  HL4379   Televisão                   5          Caio

       Sobrenome        Data            Loja  Preco Unitario  Unnamed: 8
0     Alfradique   2/25/2018  Belo Horizonte            2500         NaN
1          Rubim   2/20/2018  Belo Horizonte            2500         NaN
2        Pedrosa    7/7/2018  Belo Horizonte            5300         NaN
3          Lemos  12/26/2018  Belo Horizonte            5300         NaN
4        Botelho    6/8/2018  Belo Horizonte            3500         NaN
...          ...         ...             ...             ...         ...
2221      Junior   4/14/2018       São Paulo            1400         NaN
2222      Puntel    5/2/2018       São Paulo            5300         NaN
2223      Vianna   3/18/2018       São Paulo            5300         NaN
2224      Soares  11/21/2018       São Paulo            1400         NaN
2225      Moraes   1/22/2018       São Paulo            2500         NaN

[9999 rows x 10 columns]
            Quantidade Vendida
Produto
iPhone                    8974
Televisão                 5931
Notebook                  3249
Android                   3183
SmartWatch                2980
Tablet                    2921
Câmera                    2805
      Unnamed: 0     SKU     Produto  Quantidade Vendida Primeiro Nome  \
0             17  HL4379   Televisão                   2      Carolina
1             25  HL4379   Televisão                   1        Danilo
2             27  HL1918      iPhone                   5       Bernard
3             54  HL1918      iPhone                   5         Lucas
4             67  HL8851    Notebook                   5      Bernardo
...          ...     ...         ...                 ...           ...
2221        9981  HL7348  SmartWatch                   4          João
2222        9984  HL1918      iPhone                   4          Itai
2223        9985  HL1918      iPhone                   1     Guilherme
2224        9991  HL7348  SmartWatch                   5       Antônio
2225        9996  HL4379   Televisão                   5          Caio

       Sobrenome        Data            Loja  Preco Unitario  Unnamed: 8  \
0     Alfradique   2/25/2018  Belo Horizonte            2500         NaN
1          Rubim   2/20/2018  Belo Horizonte            2500         NaN
2        Pedrosa    7/7/2018  Belo Horizonte            5300         NaN
3          Lemos  12/26/2018  Belo Horizonte            5300         NaN
4        Botelho    6/8/2018  Belo Horizonte            3500         NaN
...          ...         ...             ...             ...         ...
2221      Junior   4/14/2018       São Paulo            1400         NaN
2222      Puntel    5/2/2018       São Paulo            5300         NaN
2223      Vianna   3/18/2018       São Paulo            5300         NaN
2224      Soares  11/21/2018       São Paulo            1400         NaN
2225      Moraes   1/22/2018       São Paulo            2500         NaN

      Faturamento
0            5000
1            2500
2           26500
3           26500
4           17500
...           ...
2221         5600
2222        21200
2223         5300
2224         7000
2225        12500

[9999 rows x 11 columns]
            Unnamed: 0  Quantidade Vendida  Preco Unitario  Unnamed: 8  \
Produto
Android        5164013                3183         3631200         0.0
Câmera         4848296                2805         2020200         0.0
Notebook       5393100                3249         3717000         0.0
SmartWatch     4968367                2980         1393000         0.0
Tablet         4920118                2921         1556800         0.0
Televisão      9675708                5931         4905000         0.0
iPhone        15015399                8974        15778100         0.0

            Faturamento
Produto
Android        10822200
Câmera          5890500
Notebook       11371500
SmartWatch      4172000
Tablet          4673600
Televisão      14827500
iPhone         47562200
            Faturamento
Produto
iPhone         47562200
Televisão      14827500
Notebook       11371500
Android        10822200
Câmera          5890500
Tablet          4673600
SmartWatch      4172000
                Unnamed: 0  Quantidade Vendida  Preco Unitario  Unnamed: 8  \
Loja
Belo Horizonte     3315042                1925         2150200         0.0
Curitiba           3383878                2151         2337200         0.0
Fortaleza          7409204                4320         4719600         0.0
Goiás              3583622                2242         2421700         0.0
Porto Alegre       3570037                2103         2305300         0.0
Recife             3631207                2208         2410500         0.0
Rio de Janeiro     7221758                4393         4970300         0.0
Salvador           6645866                4027         4345900         0.0
São Paulo         11224387                6674         7340600         0.0

                Faturamento
Loja
Belo Horizonte      6480300
Curitiba            7060500
Fortaleza          14087900
Goiás               7441800
Porto Alegre        6868600
Recife              7303000
Rio de Janeiro     14867800
Salvador           13111300
São Paulo          22098300

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed